name: Build Meme Machine

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    
    steps:
    - uses: actions/checkout@v3
    - name: Update Rust
      run: rustup update stable && rustup default stable

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        
    - name: Install packages
      run: npm install

    - name: Install ubuntu deps
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install -y libwebkit2gtk-4.0-dev libgtk-3-dev libappindicator3-dev librsvg2-dev

    - name: Build Vue
      run: npm run build
        
    - name: Build Tauri
      run: npm run tauri build
      
    - uses: actions/upload-artifact@v2
      if: matrix.os == 'ubuntu-latest'
      with:
        name: linux artifacts
        path: ./src-tauri/target/release/bundle/appimage/meme-machine_*.AppImage
    - uses: actions/upload-artifact@v2
      if: matrix.os == 'windows-latest'
      with:
        name: windows artifacts
        path: ./src-tauri/target/release/bundle/msi/*
    - uses: actions/upload-artifact@v2
      if: matrix.os == 'macos-latest'
      with:
        name: macos artifacts
        path: ./src-tauri/target/release/bundle/macos/*
