name: Build Meme Machine

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    
    steps:
    - uses: actions/checkout@v3
    - name: Update Rust
      run: rustup update stable && rustup default stable

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        
    - name: Install packages
      run: npm install

    - name: Build Vue
      run: npm run build
        
    - name: Build Tauri
      run: npm run tauri build
      
